Making requested changes
nhorman/testrepo pull request #2
Opened 2024-09-27 14:19 UTC by nhorman

making requested changes

2024-09-27 14:25 UTC, nhorman reviewed
test review comment

2024-09-27 14:32 UTC, nh-think-freely approved these changes
approved

2024-09-27 14:36 UTC, nh-think-freely approved these changes
approved

2024-09-27 14:36 UTC, nhorman commented
@nh-think-freely ping

2024-09-27 14:38 UTC, nh-think-freely approved these changes
approved

2024-09-27 14:59 UTC, nh-think-freely commented
test comment

2024-09-27 16:49 UTC, nh-think-freely commented
test comment

2024-09-29 18:57 UTC, nh-think-freely approved these changes, later dismissed
aspproved

2024-09-29 19:02 UTC, nh-think-freely approved these changes
approved again

2024-09-29 19:04 UTC, nh-think-freely requested changes, later dismissed

2024-09-29 19:04 UTC, nh-think-freely commented on README.md
> +MAKE CHANGES HERE
did you mean to do this?

2024-09-30 13:01 UTC, nh-think-freely submitted a review, later dismissed

2024-09-30 13:08 UTC, nh-think-freely approved these changes, later dismissed

2024-09-30 13:13 UTC, nh-think-freely approved these changes, later dismissed

2024-09-30 13:18 UTC, nh-think-freely approved these changes, later dismissed

2024-09-30 14:13 UTC, nh-think-freely approved these changes, later dismissed

2024-09-30 14:47 UTC, nh-think-freely approved these changes, later dismissed

2024-09-30 14:58 UTC, nh-think-freely submitted a review, later dismissed

2024-09-30 15:04 UTC, nh-think-freely approved these changes, later dismissed

2024-10-01 09:11 UTC, nh-think-freely submitted a review, later dismissed

2024-10-01 15:12 UTC, nh-think-freely approved these changes, later dismissed

2024-10-01 20:07 UTC, nh-think-freely approved these changes, later dismissed

2024-10-02 15:27 UTC, nh-think-freely submitted a review, later dismissed

2024-10-02 17:05 UTC, nh-think-freely requested changes, later dismissed

2024-10-02 17:05 UTC, nh-think-freely commented on README.md
> +
extra space

2024-10-02 17:31 UTC, nh-think-freely requested changes, later dismissed

2024-10-02 17:31 UTC, nh-think-freely commented on README.md
>  test repo for workflow development
wrong title

2024-10-02 17:36 UTC, nh-think-freely submitted a review, later dismissed

2024-10-02 17:36 UTC, nh-think-freely commented on README.md
>  test repo for workflow development
still not right

2024-10-02 17:42 UTC, nh-think-freely approved these changes, later dismissed

2024-10-02 18:09 UTC, nh-think-freely approved these changes, later dismissed

2024-10-02 18:16 UTC, nh-think-freely submitted a review, later dismissed

2024-10-02 18:16 UTC, nh-think-freely commented on README.md
> +
still not right

2024-10-02 18:21 UTC, nh-think-freely submitted a review, later dismissed

2024-10-02 18:21 UTC, nh-think-freely commented on README.md
> +
nope

2024-10-02 18:23 UTC, nh-think-freely requested changes

2024-10-02 18:23 UTC, nh-think-freely commented on README.md
> +
nope nope

2024-10-02 18:24 UTC, nh-think-freely approved these changes

2026-04-16 00:41 UTC, closed without merging